spring.application.name=QuickRide
server.port=1100

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ride_booking_system
spring.datasource.username=postgres
spring.datasource.password=bharti
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable Config Server/Eureka for Local Testing
spring.cloud.config.enabled=false
eureka.client.enabled=false

# Redis Settings (DOCKER COMPATIBLE)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
# Docker Redis by default has NO password. Comment this out:
# spring.data.redis.password=bharti

spring.data.redis.repositories.enabled=false
spring.data.redis.client-type=lettuce

# Kafka Settings
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.consumer.group-id=quickride-group
spring.kafka.consumer.auto-offset-reset=earliest